version: 2
models:
  - name: stg_stock_prices
    columns:
      - name: symbol
        tests:
          - not_null
      - name: trade_date
        tests:
          - not_null
  - name: silver_stock_prices
    columns:
      - name: symbol
        tests:
          - not_null
      - name: trade_date
        tests:
          - not_null
      - name: close_price
        tests:
          - not_null
  - name: fact_stock_returns_daily
    columns:
      - name: symbol
        tests:
          - not_null
      - name: trade_date
        tests:
          - not_null